name: amap_flutter_base
description: 高德开放平台，Flutter插件，基础依赖库.
version: 3.0.0
homepage: https://lbs.amap.com/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
